---
comment:
  image:
    repository: playjim/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: playjim/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: playjim/ui
    tag: latest
  service:
    externalPort: 9292

mongodb:
  usePassword: false
