version: '3.3'
services:
  post_db:
    image: mongo:${TAGDB}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    image: ${USERNAME}/ui:${TAG}
    ports:
      - ${PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${TAG}
    networks:
      - back_net
      - front_net

  comment:
    image: ${USERNAME}/comment:${TAG}
    networks:
      - back_net
      - front_net
    links:
      - "post_db:comment_db"


volumes:
  post_db:
  prometheus_data:
    
networks:
  back_net:
  front_net:
