{
 "title": "UI Service Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP response time 95th percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))",
     "legendFormat": "{{ ui_request_response_time_bucket }}"
    }
   ]
  },
  {
   "title": "UI HTTP requests",
   "type": "graph",
   "description": "All HTTP requests that UI service receives",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[23].*\"}[1m])",
     "legendFormat": "{{ http_status }} {{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP Requests with error",
   "type": "graph",
   "description": "Rate of UI HTTP Requests with code error 4* and 5*",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])",
     "legendFormat": "{{ http_status }} {{ method }} {{ path }}"
    }
   ]
  }
 ]
}